const {
  presenceLocationWorkAdd,
  presenceLocationWorkDelete,
  presenceLocationWorkDetail,
  presenceLocationWorkEdit,
  presenceLocationWorkAll,
  presenceLocationWorkPagination,
  presenceLocationWorkRestore,
} = require("./presenceLocationWork");
const {
  presenceEmployeeAdd,
  presenceEmployeeAll,
  presenceEmployeeDelete,
  presenceEmployeeDetail,
  presenceEmployeeDetailByUser,
  presenceEmployeeEdit,
  presenceEmployeePagination,
  presenceEmployeeRestore,
  presenceEmployeeScheduleNow,
} = require("./presenceEmployee");
const {
  presenceListDayAdd,
  presenceListDayAll,
  presenceListDayDelete,
  presenceListDayDetail,
  presenceListDayEdit,
  presenceListDayPagination,
  presenceListDayRestore,
} = require("./presenceListDay");
const {
  presenceScheduleEmployeeAddMultiple,
  presenceScheduleEmployeeAddSingle,
  presenceScheduleEmployeeDelete,
  presenceScheduleEmployeeDetail,
  presenceScheduleEmployeeEdit,
  presenceScheduleEmployeePagination,
  presenceScheduleEmployeeRestore,
} = require("./presenceScheduleEmployee");

module.exports = {
  presenceLocationWorkAdd,
  presenceLocationWorkDelete,
  presenceLocationWorkDetail,
  presenceLocationWorkEdit,
  presenceLocationWorkAll,
  presenceLocationWorkPagination,
  presenceLocationWorkRestore,
  presenceEmployeeAdd,
  presenceEmployeeAll,
  presenceEmployeeDelete,
  presenceEmployeeDetail,
  presenceEmployeeDetailByUser,
  presenceEmployeeEdit,
  presenceEmployeePagination,
  presenceEmployeeRestore,
  presenceEmployeeScheduleNow,
  presenceListDayAdd,
  presenceListDayAll,
  presenceListDayDelete,
  presenceListDayDetail,
  presenceListDayEdit,
  presenceListDayPagination,
  presenceListDayRestore,
  presenceScheduleEmployeeAddMultiple,
  presenceScheduleEmployeeAddSingle,
  presenceScheduleEmployeeDelete,
  presenceScheduleEmployeeDetail,
  presenceScheduleEmployeeEdit,
  presenceScheduleEmployeePagination,
  presenceScheduleEmployeeRestore,
};
